---
title: "Python - Introduction"
author: "Brendan LE LAIN"
date: "20 janvier 2019"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618  # 1 / phi
)
```

# Sources

* <https://docs.python.org/2/tutorial/introduction.html>

# Opérations de base

* commentaire : `#`
* assignation : `=`
* int : `a = 2`
* float : `a = 2.0`
* division classique : `/`

```{python}
print(5/2)
print(5/2.0)
```

* division entière `//`

```{python}
print(5//2)
```

* reste de la division : `%`

```{python}
print(5 % 2)
```

* puissance : `**`

```{python}
print(3**3)
```

* en mode console, le résultat de la dernière opération est stockée dans la variable `_`

# String

* quotes simple ou double

```{python}
print('une chaine l\'agneau')
print("l'agneau")
```

* concaténation : `+`
* répétition : `*`

```{python}
print(3 * "un" + "deux")
```

* string sur plusieurs lignes : `""" ... """`
* 2 strings côte à côte sont concaténés, marche seulement pour des strings (pas des variables). Pratique pour découper des strings longs

```{python}
text = ('Put several strings within parentheses '
        'to have them joined together.')
print(text)
```

* un string est indexable, commence par l'indice 0 :

```{python}
text = "Python"
print(text[0])
print(text[5])
```

* indice négatif pour compter de la fin

```{python}
print(text[-1])
```

* on peut avoir des sous-chaines avec `:`

```{python}
# des défaut pratiques :
print(text[0:2]) # 0 inclut, 2 exclut
print(text[:3])
print(text[-2:])
```

* on ne peut pas changer directement une chaine

```{}
# erreur
# text[2] = "x"   
```

* fonction `len()` pour avoir la taille du string

```{python}
print(len(text))
```

# Listes

* peut être de type différent, mais c'est souvent le meme type

```{python}
une_list = [1, 2, 3]
```

* peut être indéxé comme les strings 

```{python}
print(une_list[0])  # renvoie un int
print(une_list[:2])  # renvoie une liste
```

* les listes acceptent la concaténation

```{python}
print(une_list + [4, 5])
```

* les listes sont *mutables* (contrairement aux strings) : on peut changer leur valeur

```{python}
une_list[1] = 88
print(une_list)
```

* on peut ajouter un élément avec la *méthode* `append()`

```{python}
une_list.append(100)
print(une_list)
```

* on peut assigner à des *slices*, ça peut changer la taille de la liste ou même la vider complètement

```{python}
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(letters)

letters[2:5] = ['C', 'D', 'E']
print(letters)

letters[2:5] = []
print(letters)

letters[:] = []
print(letters)
```

* on peut aussi utiliser la fonction `len()` pour les listes
```{python}
print(len(letters))
```

* on peut imbriquer les listes

```{python}
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
print(x)

print(x[0])

print(x[0][1])
```

## Méthodes des objets *list*

* `list.append(x)` : ajoute un élément à la fin

* `list.extend(L)` : ajoute les éléments de L à la fin

* `list.insert(i, x)` : insert un élément avant la position donnée. `a.insert(0, x)` insert au début, `a.insert(len(a), x)` est équivalent à `a.append(x)`.

* `list.remove(x)` : supprime le premier élément de la liste dont la valeur est `x`.

* `list.pop([i])` : supprime l'élément à la position donnée, et renvoie cet élément. Si aucun indice n'est spécifié, `a.pop()` supprime et renvoie le dernier élément de la liste. (Les crochets dans la signature signifie que l'argument est optionnel). 

```{python}
a = [1, 3, 5]
print(a.pop(1))
print(a)

print(a.pop())
print(a)
```

* `list.index(x)` : renvoie l'indice du premier élément de la liste dont la valeur est `x`.

* `list.count(x)` : renvoie le nombre de fois où `x` apparaît dans la liste.

* `list.sort(cmp=None, key=None, reverse=False)` : tri les éléments de la liste, voir <https://docs.python.org/2.7/library/functions.html#sorted> pour explication des arguments.

* `list.reverse()` : inverse les éléments de la liste.

## Listes comme *stacks*

* stack : une liste où le dernier élément ajouté est le premier à partir ("last-in, first-out"). 
* Pour ajouter un élément sur le haut du stack, utiliser `append()`
* Pour retirer un élément du haut du stack, utiliser `pop()`

## Listes comme *queues*

* queue : une liste où le premier élément ajouté est le premier à partir ("first-in, first-out"). 
* *list* pas très efficace pour insérer au début car il faut décaler tous les éléments.
* pour implémenter une *queue*, utiliser `collections.deque` qui permet des *appends* et *pops* rapides des 2 côtés.

```[python}
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives
print(queue)
queue.popleft()                 # The first to arrive now leaves
print(queue)
queue.popleft()                 # The second to arrive now leaves
print(queue)        
```

## Outils pour la programmation fonctionnelle

* 3 fonctions très utiles avec les listes : `filter()`, `map()` et `reduce()`.

### `filter()`

* `filter(function, sequence)` renvoie une séquence construites avec les éléments de la séquence pour lesquels `function(item)` est *True*.
* Si *sequence* est `str`, `unicode` ou `tuple`, le résultat sera du même type. Sinon, le résultat est toujours une liste.

```{python}
# les nombres divisible par 3 ou 5
def f(x): return x % 3 == 0 or x % 5 == 0

print(filter(f, range(2, 25)))
```

### `map()`

* `map(function, sequence)` appelle `function(item)` pour chaque élément de la séquence et renvoie une liste des éléments renvoyés.

```{python}
# pour calculer quelques cubes
def cube(x): return x*x*x

print(map(cube, range(1, 11)))
```

* il est possible de passer plusieurs séquences, alors la fonction doit avoir autant d'arguments que de séquences.

```{python}
seq = range(8)
def add(x, y): return x+y

print(map(add, seq, seq))
```

### `reduce()`

* `reduce(function, sequence)` renvoie une seule valeur construite en appelant la fonction binaire (2 arguments) `function` sur les 2 premiers éléments de la séquence, puis sur le résultat et l'élément suivant, etc.

```{python}
def add(x, y): return x + y

print(reduce(add, range(1, 4))
```

* un troisième argument peut être passé pour indiquer la valeur de départ.

## *List comprehensions*

* permet de créer des listes où chaque élément est le résultat d'une opération ou satisfait une condition.
* créer avec `[]` et un `for` suivi de zéro ou plusieurs `for` ou `if`.

Des exemples : 

```{python}
print([x**2 for x in range(10)])

print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])

vec = [-4, -2, 0, 2, 4]

# create a new list with the values doubled
print([x*2 for x in vec])

# filter the list to exclude negative numbers
print([x for x in vec if x >= 0])

# apply a function to all the elements
print([abs(x) for x in vec])

# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
print([weapon.strip() for weapon in freshfruit])

# create a list of 2-tuples like (number, square)
print([(x, x**2) for x in range(6)])

# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
print([num for elem in vec for num in elem])
```

## `del` statement

* permet de supprimer une ou plusieurs valeur(s) d'une liste
* peut aussi supprimer un objet entier

```{python}
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
print(a)

del a[2:4]
print(a)

del a[:]
print(a)

del a
```
 
# Tuples et Sequences

* les strings et listes sont 2 exemples de types *sequence*. Le *tuple* en est un autre.
* un tuple est un ensemble de valeurs (pouvant être de types différents) séparées par des virgules 
* les tuples sont *immutable* (changer une valeur avec indice interdit : `t[0] = 1` renvoie une erreur). 

```{python}
t = 12345, 54321, 'hello!'
print(t[0])
print(t)

# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
print(u)

# Tuples are immutable:
# t[0] = 88888  # erreur

# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
print(v)
```

* différences avec les listes
    + les tuples sont immutable, contiennent souvent des éléments hétérogènes, auxquels on accède par *unpacking* ou indices.
    + les listes sont mutables, contiennent souvent des éléments de même type, auxquels on accède par itération sur la liste.
* un tuple vide se construit avec une paire de parenthèses
* un tuple avec une seule valeur se construit avec une valeur suivie d'une parenthèse

```{python}
empty = ()
singleton = 'hello',    # <-- note trailing comma
print(len(empty))

print(len(singleton))
print(singleton)
```

* packing et unpacking :
    + packing : `t = 1, 2, 'abc'`, les 3 valeurs sont rassembler dans un tuple
    + unpacking : `x, y, z = t`. Fonctionne pour n'importe quelle séquence `t` ; nécessite que les variables à gauche du signe égal soient du même nombre que la taille de la séquence.   

# Sets

* un *set* est une collection non ordonnée sans doublons
* les sets supportent les opérations comme l'union, l'intersection et la différence
* pour créer un set : 
    + soit les `{}`
    + soit la fonction `set()`
* pour créer un set vide, il faut utiliser `set()`. Si on utilise `{}` cela crée un dictionnaire vide.

```{pyhton}
# une liste
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
fruit = set(basket)    # create a set without duplicates
print(fruit)

print('orange' in fruit)    # fast membership testing
print('crabgrass' in fruit)

# Demonstrate set operations on unique letters from two words
a = set('abracadabra')
b = set('alacazam')
print(a)  # unique letters in a

print(a - b)  # letters in a but not in b

print(a | b)  # letters in either a or b

print(a & b)  # letters in both a and b

print(a ^ b)  # letters in a or b but not both   
```

* comme pour les *list comprehensions*, les *set comprehensions* sont aussi supportés :

```{python}
a = {x for x in 'abracadabra' if x not in 'abc'}
print(a)
```

# Dictionnaires

* les dictionnaires sont indéxés par des *clés* qui peuvent être n'importe quel type immutable, en général des strings ou nombres.
* on peut penser à un dictionnaire comme à un set de paires *clé: valeur*, avec la nécessité que les clés soient uniques (dans un dictionnaire).
* `{}` pour créer un dictionnaire vide.
* pour ajouter des valeurs initiales au dictionnaire, ajouter dans les accolades une liste de *clé: valeur* séparés par des `,`.
* pour supprimer une paire *clé: valeur*, utiliser `del`.
* `keys()` permet de récupérer toutes les clés du dictionnaire dans un ordre arbitraire (utiliser `sorted()` pour les trier).
* `in` pour tester si une valeur est une clé du dictionnaire.

```{python}
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127  # ajouter une paire clé:valeur
print(tel)

print(tel['jack'])

del tel['sape']
tel['irv'] = 4127
print(tel)

print(tel.keys())

print('guido' in tel)
```

* le constructeur `dict()` pour créer un dictionnaire à partir d'une séquence :

```{python}
d = dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])
print(d)
```

* les dictionnaires comprehensions peuvent aussi être utilisés :

```{python}
d = {x: x**2 for x in (2, 4, 6)}
print(d)
```

* quand les clés sont simples, on peut les spécifier en utilisant des arguments (sans quotes) : 

```{python}
d = dict(sape=4139, guido=4127, jack=4098)
print(d)
```

# Programmation

* assignation multiple

```{python}
a, b = 0, 1
print(a)
print(b)
```

* mais on ne peut pas faire 

```{pyhton}
# erreur :
# a, b = 0
```

* les expressions à droite de l'assignation sont évaluées en premier
* l'indentation joue le rôle des accolades

```{python}
# Fibonacci series:
# the sum of two elements defines the next
a, b = 0, 1
while b < 10:
   print(b)
   a, b = b, a+b
```

## Conditions 

### if 

* `elif` pour "else if"

```{python}
x = 42
if x < 0:
  x = 0
  print 'Negative changed to zero'
elif x == 0:
  print 'Zero'
elif x == 1:
  print 'Single'
else:
  print 'More'
```

### `in`

* teste si une séquence contient une certaine valeur 
* `not in` pour le contraire

```{pyton}
print('ok' in ('o', 'k'))
print('ok' not in ('o', 'k'))
```

### `is`

* teste si 2 objets sont les mêmes
* `is not` pour le contraire

```{pyton}
print(['a', 'b'] is ['b', 'a'])
print(['a', 'b'] is not ['b', 'a'])
```

### Chaînage des opérateurs de comparaison

* on peut chaîner les opérateurs de comparaison : `x != y != z` est équivalent à `x != y and y != z`.

### Comparaison de séquence

* les séquences (tuples, lists, strings en particulier) sont comparés élément par élément : 

```{python}
print((1, 2, 3)              < (1, 2, 4))
print([1, 2, 3]              < [1, 2, 4])
print('ABC' < 'C' < 'Pascal' < 'Python')
print((1, 2, 3, 4)           < (1, 2, 4))
print((1, 2)                 < (1, 2, -1))
print((1, 2, 3)             == (1.0, 2.0, 3.0))
print((1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4))
```

## Boucles

### for 

* Ressemble au `for` de R, on peut itérer aussi bien sur une suite d'entiers que sur une liste ou un string

```{python}
words = ['cat', 'window', 'defenestrate']
for w in words:
  print w, len(w)
```

```{python}
for w in words[:]:  # Loop over a slice copy of the entire list.
  if len(w) > 6:
    words.insert(0, w)
print(words)
```

* quand on boucle sur une séquence, on peut obtenir en même temps l'indice et la valeur correspondante avec `enumerate()` : 

```{python}
for i, v in enumerate(['tic', 'tac', 'toe']):
    print i, v
```

* quand on souhaite boucler sur 2 (ou plus) séquences à la fois, on peut utiliser la fonction `zip()` qui assemble les séquences : 

```{python}
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
print(zip(questions, answers))

for q, a in zip(questions, answers):
    print 'What is your {0}?  It is {1}.'.format(q, a)
```

* pour boucler à l'envers sur une séquence, utiliser la fonction `reversed()` : 

```{python}
for i in reversed(range(1,10,2)):
    print i
```

* quand on boucle sur un dictionnaire, la clé et la valeur correspondante peuvent être obtenues en même temps avec `iteritems()` : 

```{python}
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.iteritems():
    print k, v
```

* au lieu de changer une liste lorsqu'on boucle dessus, il est souvent plus simple et rapide de créer une nouvelle liste : 

```{python}
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

print(filtered_data)
```



## La fonction `range()`

* Surtout utile pour les for, permet de générer une séquence d'entiers, renvoie une liste
* avec un seul argument `stop` : liste qui débute à 0 de taille `stop`
* avec 2 arguments `start`, `stop` : commence à `start` inclut, finit à `stop` exclut 
* avec 3 arguments `start`, `stop`, `step`
* tous les arguments doivent être des entiers

```{python}
range(10)
range(5, 10)
range(0, 10, 3)
```
Voir <https://docs.python.org/2.7/library/functions.html#range> pour documentation.

## `pass`

* `pass` ne fait rien
* souvent utilisé pour créer une classe minimale 

```{python}
class MyEmptyClass:
    pass
```

* peut être utilisé aussi pour définir une fonction de façon minimale

```{python}
def initlog(*args):
    pass  # penser à faire ça !
```


# Fonctions

* avec le mot clé `def`
* on peut mettre sur la première ligne un *docstring* pour documenter la fonction, c'est juste un string, plutôt avec `""" ... """`.
* une fonction sans `return` renvoie une valeur `None`

```{python}
def fib(n):
  """Print a Fibonacci series up to n."""
  a, b = 0, 1
  while a < n:
    print a,  # la virgule pour imprimer à la suite (sinon c'est à la ligne)
    a, b = b, a+b

# Now call the function we just defined:
fib(2000)
```

* La même mais en renvoyant le résultat dans une liste :

```{python}
def fib2(n):  
  """Return a list containing the Fibonacci series up to n."""
  result = []
  a, b = 0, 1
  while a < n:
    result.append(a)  
    a, b = b, a+b
  return result
  
print(fib2(100))
```
* `append()` est une méthode définie pour les listes, permet d'ajouter un élément à la fin de la liste. 
* une fonction peut avoir un argument par défaut avec `=`

## argument de la forme `*name`

Pour construction d'une fonction :

* reçoit un *tuple*
* équivalent au `...` de R : reçoit un nombre indéterminé d'arguments qui sont mis dans un tuple

Pour l'appel d'une fonction :

* l'opérateur `*` permet de donner à une fonction des arguments contenus dans une liste

```{python}
print(range(3, 6))  # normal call with separate arguments

args = [3, 6]
print(range(*args)) 
```

## argument de la forme `**name`

Pour construction d'une fonction :

* reçoit un *dictionary* 

```{pyhton}
def cheeseshop(kind, *arguments, **keywords):
    print "-- Do you have any", kind, "?"
    print "-- I'm sorry, we're all out of", kind
    for arg in arguments:
        print arg
    print "-" * 40
    keys = sorted(keywords.keys())
    for kw in keys:
        print kw, ":", keywords[kw]

print(cheeseshop("Limburger", 
                 "It's very runny, sir.",
                 "It's really very, VERY runny, sir.",
                 shopkeeper='Michael Palin',
                 client="John Cleese",
                 Cheese="sketch Shop Sketch"))
```

Pour l'appel d'une fonction :

* un dictionary permet d'appeler une fonction

```{python}
def parrot(voltage, state='a stiff', action='voom'):
    print "-- This parrot wouldn't", action,
    print "if you put", voltage, "volts through it.",
    print "E's", state, "!"

d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}

print(parrot(**d))
```

## lambda fonction

* permet d'écrire des petites fonctions anonyme
* avec le mot clé `lambda` 
* exemple : `lambda a, b: a + b`

## Documentation strings

* sur la première ligne da définition de la fonction
* doit être bref et résumer l'objectif de la fonction
* cette ligne doit commencer par une majuscule et terminer par un point 
* si il y a plusieurs lignes, la première doit être séparée du reste par une ligne vide

```{python}
def my_function():
    """Do nothing, but document it.

    No, really, it doesn't do anything.
    """
    pass

print(my_function.__doc__)
```

# Classes

* Exemple simple qui définit 2 attributs `MyClass.i` (un entier) et `MyClass.f` (une fonction) :

```{python}
class MyClass:
    """A simple example class"""
    i = 12345

    def f(self):
        return 'hello world'
```

* `MyClass.__doc__` renvoie la docstring de la classe.

* on peut instantier une classe avec `x = MyClass()`.
* si on appelle `MyClass.f(x)` on a un appel de fonction. Si on appelle `x.f()` on a un appelle de méthode.
* pour une instantiation personnaliser, il faut définir la méthode `__init__()` : 

```{python}
class Complex:
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart

x = Complex(3.0, -4.5)
print(x.r, x.i)
```



# Coding style

Voir <https://www.python.org/dev/peps/pep-0008/> pour le style guide complet.

* utiliser une indentation avec 4 espaces, pas de tabulation
* faire des lignes de 79 caractères maximum
* lignes vides pour séparer les fonctions et les classes, et des blocs de code plus importants pour le corps des fonctions
* utiliser la docstrings
* nomage des classes : `CamelCase`
* nomage des fonctions : `lower_case_with_underscores`


# Modules

* Un module est un fichier `.py` contenant des définitions en Python.
* Le nom du fichier est le nom du module, qui est accessible avec la variable globale `__name__`.
* pour importer un module : `import nom_module`.
* puis pour utiliser les fonctions de ce module : `nom_module.nom_fonction()`

## `import`

* pour importer seulement quelques fonctions du module : `from nom_module import f_1, f_2`. Cela permet d'appeler `f_1()` sans `nom_module.` devant.

* pour importer toutes les fonctions du module sauf celles commençant par `_` : `from nom_module import *`. (Plutôt déconseillé).

* pour changer le nom de référence du module : `import nom_module as mod`. Permet d'appeler `f_1()` avec `mod.f_1()`.

## fonction `dir()`

* sans argument, renvoie les noms que l'on a défini
* avec un module en argument, renvoie les noms que ce module définis
* pour avoir le noms des *built-in* fonctions et variables, c'est dans le module `__builtin__` : faire `dir(__builtin__)`. 

## Package

* un package est un ensemble de modules.
* c'est un répertoire qui doit comprendre un fichier `__init__.py` et d'autres répertoires avec des fichiers `.py` (=modules). 

## Input et output

* voir la fonction `str.format()` pour formatter des strings (<https://docs.python.org/2.7/library/stdtypes.html#str.format>). 
* ajouter `:` puis un format pour gérer la manière dont la valeur sera imprimée (voir <https://docs.python.org/2.7/library/string.html#formatstrings>.

```{python}
# Entre accolades, peut mettre soit un indice ou un argument 
"The sum of 1 + 2 is {0}".format(1+2)
"The sum of 2 * 3.333 is {res:.2f}".format(res = 2*3.333)
```
 
* `repr()` ou `str()` pour convertir un objet en string
* `str.rjust()`, `str.ljust()` et `str.center()` : pour justifier à droite, gauche, centre pour un champs d'une largeur donné et ajoutant dans espaces où il faut.
* `str.zfill()` pour padding un string numérique avec des zéros à gauche.

### Lire et écrire des fichiers

* la fonction `open()` renvoie un objet *file*. En général 2 arguments : `open(filename, mode)`.
* `mode` peut être :
    + `'r'` pour read only (par défaut)
    + `'w'` pour write only
    + `'a'` pour append
    + `'r+'` pour read et write

* pour un objet file `f`, `f.read(size)` lit la quantité de données fournit. Sans argument, lit tout le fichier. Renvoie `''` quand tout le fichier a été lu.
* `f.readline()` pour lire une seule ligne du fichier. Renvoie `''` quand tout le fichier a été lu.
* Si on veut lire toutes les lignes du fichier dans une liste, on peut utiliser `list(f)` ou `f.readlines()`

* `f.write(string)` écrit le string dans le fichier, et renvoie `None`.
* `f.tell()` renvoie un entier donnant la position actuel dans le fichier. Pour changer la position dans le fichier, utiliser `f.seek(offset, from_what)` : la nouvelle position est calculée en ajoutant *offset* à la position de référence donnée par *from_what*.
    + si *from_what* = 0 : début du fichier (par défaut)
    + si *from_what* = 1 : position courrante
    + si *from_what* = 2 : fin du fichier

* `f.close()` pour fermer le fichier.
* bonne habitude d'utiliser `with` quand on travaille avec des objets *file*, permet de s'assurer que le fichier est correctement fermé : 

```{python}
with open('workfile', 'r') as f:
    read_data = f.read()

print(f.closed)
```

### JSON

* Pour sauvegarder des données contenues dans type Python, utiliser le module standard *json*. Revient à de la sérialisation.
* fonction `json.dumps()` pour avoir la représentation JSON d'un objet
* `json.dump(x, f)` pour sérialiser `x` dans le fichier `f`.
* `json.load(f)` pour lire le fichier json.

```{python}
import json
json.dumps([1, 'simple', 'list'])
```

# Exceptions

* Voir <https://docs.python.org/2.7/tutorial/errors.html>






